name: Daily LINE Notification  # ✅ これがないと表示されません！

on:
  schedule:
    - cron: '0 3 * * *'  # JST 12:00 実行 ！
  workflow_dispatch:  # ✅ 手動実行ボタンを有効にする！！

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write credentials.json
        run: |
          cat <<EOF > credentials.json
${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
EOF

      - name: Run notifier script
        run: |
          echo "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" > .env
          echo "LINE_USER_ID=${{ secrets.LINE_USER_ID }}" >> .env
          python today_notify.py
